services:
  
  php-commission-calculator:
    container_name: php-commission-calculator
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    stdin_open: true